### PR TITLE
Add membership endpoint GET support

### PR DESCRIPTION
**Pull request by paddatrapper**
Adds support for the membership endpoint (`/membership`), however as my HTTP and REST is a little rusty, it only supports the `GET` methods

### CODE REVIEW

**Comment by willkara** [comment]
Nice job! As you can tell, I haven't worked on this in years. Mainly because I left Rutgers. Feel free to improve it and make any changes you want! :)

**Comment by paddatrapper** [comment]
Thanks! This is largely so that I can use Sakai as a backend for Django authentication (https://gitlab.com/bubbles/sakaiauthenticator/) with optional site membership confirmation.

**Comment by paddatrapper** [comment]
@willkara is it possible to get a release with membership support sometime soon? That would simplify my distribution of sakaiauthenticator a lot

**Comment by willkara** [comment]
Kyle,

No problem. I'll be able to get a new release going and even update Pypy
tonight.

**Comment by paddatrapper** [comment]
Thanks a lot. It is much appreciated!

**Comment by willkara** [comment]
Hey sorry I've been really busy with work but should be able to get Pypy
updated by the end of the week

**Comment by willkara** [comment]
https://pypi.org/project/SakaiPy/2.3.0/

**Comment by paddatrapper** [comment]
Thanks a lot for all your work!

**Comment by willkara** [comment]
No problem. I haven't been involved in the Sakai community since I left Rutgers so I haven't been able to keep up on the APIs. Send me an email if you work with Sakai and maybe we can continue to work on it.

**Pull request merged**
